import { Review } from '../interfaces';

export const Reviews: Review[] = [
  {
    username: 'Тетяна',
    publicationDate: '12.22.2023',
    content:
      'Магазин килимів - справжнє відкриття! Вражаючий вибір високоякісних килимів, що вражають різноманіттям стилів та дизайнів. Обслуговування на високому рівні, де кожен працівник виявився професіоналом. Вдала покупка перевершила мої очікування - отримав точно те, що шукав. Дякую за приємний досвід покупки, рекомендую цей магазин як надійного партнера у виборі ідеального килима для вашого простору. Неперевершений вибір, висока якість та привітний персонал - ось, що робить цей магазин винятковим. Впевнено рекомендую усім, хто цінує комфорт і стиль у своєму житлі!',
    rating: 5,
  },
  {
    username: 'Тетяна',
    publicationDate: '12.22.2023',
    content:
      'Магазин килимів - справжнє відкриття! Вражаючий вибір високоякісних килимів, що вражають різноманіттям стилів та дизайнів. Обслуговування на високому рівні, де кожен працівник виявився професіоналом. Вдала покупка перевершила мої очікування - отримав точно те, що шукав. Дякую за приємний досвід покупки, рекомендую цей магазин як надійного партнера у виборі ідеального килима для вашого простору. Неперевершений вибір, висока якість та привітний персонал - ось, що робить цей магазин винятковим. Впевнено рекомендую усім, хто цінує комфорт і стиль у своєму житлі!',
    rating: 3,
  },
  {
    username: 'Тетяна',
    publicationDate: '12.22.2023',
    content:
      'Магазин килимів - справжнє відкриття! Вражаючий вибір високоякісних килимів, що вражають різноманіттям стилів та дизайнів. Обслуговування на високому рівні, де кожен працівник виявився професіоналом. Вдала покупка перевершила мої очікування - отримав точно те, що шукав. Дякую за приємний досвід покупки, рекомендую цей магазин як надійного партнера у виборі ідеального килима для вашого простору. Неперевершений вибір, висока якість та привітний персонал - ось, що робить цей магазин винятковим. Впевнено рекомендую усім, хто цінує комфорт і стиль у своєму житлі!',
    rating: 1,
  },
];

export interface Product {
  category: string;
  isDiscount?: boolean;
  manufacturer: string;
  unit_price: number;
  description: string;
  availability_status: string;
  quantity_in_stock: number;
  popularity_rating: number;
  features: string[]; // або може бути словник характеристик { [key: string]: string }
  product_image_url: string | string[]; // якщо можливо масив з фотками
  sizes: {
    size: string;
    quantity_in_stock: number;
  }[];
  rug_type: string;
  rug_material: string;
  rug_color: string | string[];
  rug_shape: string;
  rug_country_of_origin: string;
  rug_pile_height: number;
  rug_backing_material: string;
  rug_height: number;
  rug_sku: string | number;
  rug_discounted_price?: number;
}

export const Products: Product[] = [
  {
    category: 'rugs',
    isDiscount: true,
    manufacturer: 'Виробник 1',
    unit_price: 100,
    description: 'Опис першого килима',
    availability_status: 'В наявності',
    quantity_in_stock: 10,
    popularity_rating: 4.5,
    features: ['Функція 1', 'Функція 2'],
    product_image_url: 'url_to_image.jpg',
    sizes: [
      { size: 'Маленький', quantity_in_stock: 5 },
      { size: 'Великий', quantity_in_stock: 5 },
    ],
    rug_type: 'Шерстяний',
    rug_material: 'Шерсть',
    rug_color: ['Синій', 'Зелений'],
    rug_shape: 'Прямокутний',
    rug_country_of_origin: 'Туреччина',
    rug_pile_height: 10,
    rug_backing_material: 'Гума',
    rug_height: 200,
    rug_sku: 'SKU123',
    rug_discounted_price: 90,
  },
  {
    category: 'Килими',
    isDiscount: true,
    manufacturer: 'Виробник 1',
    unit_price: 100,
    description: 'Опис першого килима',
    availability_status: 'В наявності',
    quantity_in_stock: 10,
    popularity_rating: 4.5,
    features: ['Функція 1', 'Функція 2'],
    product_image_url: 'url_to_image.jpg',
    sizes: [
      { size: 'Маленький', quantity_in_stock: 5 },
      { size: 'Великий', quantity_in_stock: 5 },
    ],
    rug_type: 'Шерстяний',
    rug_material: 'Шерсть',
    rug_color: ['Синій', 'Зелений'],
    rug_shape: 'Прямокутний',
    rug_country_of_origin: 'Туреччина',
    rug_pile_height: 10,
    rug_backing_material: 'Гума',
    rug_height: 200,
    rug_sku: 'SKU123',
    rug_discounted_price: 90,
  },
  {
    category: 'Килими',
    manufacturer: 'Виробник 1',
    unit_price: 120,
    description: 'Опис другого килима',
    availability_status: 'В наявності',
    quantity_in_stock: 8,
    popularity_rating: 4.2,
    features: ['Функція 3', 'Функція 4'],
    product_image_url: 'url_to_image2.jpg',
    sizes: [
      { size: 'Маленький', quantity_in_stock: 4 },
      { size: 'Великий', quantity_in_stock: 4 },
    ],
    rug_type: 'Синтетичний',
    rug_material: 'Синтетика',
    rug_color: ['Чорний', 'Сірий'],
    rug_shape: 'Прямокутний',
    rug_country_of_origin: 'Туреччина',
    rug_pile_height: 8,
    rug_backing_material: 'Тканина',
    rug_height: 180,
    rug_sku: 'SKU456',
    rug_discounted_price: 110,
  },
  {
    category: 'Килими',
    manufacturer: 'Виробник 2',
    unit_price: 90,
    description: 'Опис третього килима',
    availability_status: 'В наявності',
    quantity_in_stock: 12,
    popularity_rating: 4.7,
    features: ['Функція 5', 'Функція 6'],
    product_image_url: 'url_to_image3.jpg',
    sizes: [
      { size: 'Маленький', quantity_in_stock: 6 },
      { size: 'Великий', quantity_in_stock: 6 },
    ],
    rug_type: 'Шерстяний',
    rug_material: 'Шерсть',
    rug_color: ['Червоний', 'Жовтий'],
    rug_shape: 'Круглий',
    rug_country_of_origin: 'Індія',
    rug_pile_height: 12,
    rug_backing_material: 'Гума',
    rug_height: 220,
    rug_sku: 'SKU789',
    rug_discounted_price: 85,
  },
  {
    category: 'Килими',
    manufacturer: 'Виробник 3',
    unit_price: 80,
    description: 'Опис четвертого килима',
    availability_status: 'В наявності',
    quantity_in_stock: 15,
    popularity_rating: 4.4,
    features: ['Функція 7', 'Функція 8'],
    product_image_url: 'url_to_image4.jpg',
    sizes: [
      { size: 'Маленький', quantity_in_stock: 7 },
      { size: 'Великий', quantity_in_stock: 8 },
    ],
    rug_type: 'Синтетичний',
    rug_material: 'Синтетика',
    rug_color: 'Зелений',
    rug_shape: 'Овальний',
    rug_country_of_origin: 'Китай',
    rug_pile_height: 9,
    rug_backing_material: 'Тканина',
    rug_height: 170,
    rug_sku: 'SKU101',
    rug_discounted_price: 75,
  },
  {
    category: 'Килими',
    manufacturer: 'Виробник 3',
    unit_price: 80,
    description: 'Опис четвертого килима',
    availability_status: 'В наявності',
    quantity_in_stock: 15,
    popularity_rating: 4.4,
    features: ['Функція 7', 'Функція 8'],
    product_image_url: 'url_to_image4.jpg',
    sizes: [
      { size: 'Маленький', quantity_in_stock: 7 },
      { size: 'Великий', quantity_in_stock: 8 },
    ],
    rug_type: 'Синтетичний',
    rug_material: 'Синтетика',
    rug_color: 'Зелений',
    rug_shape: 'Овальний',
    rug_country_of_origin: 'Китай',
    rug_pile_height: 9,
    rug_backing_material: 'Тканина',
    rug_height: 170,
    rug_sku: 'SKU101',
    rug_discounted_price: 75,
  },
  {
    category: 'Килими',
    manufacturer: 'Виробник 3',
    unit_price: 80,
    description: 'Опис четвертого килима',
    availability_status: 'В наявності',
    quantity_in_stock: 15,
    popularity_rating: 4.4,
    features: ['Функція 7', 'Функція 8'],
    product_image_url: 'url_to_image4.jpg',
    sizes: [
      { size: 'Маленький', quantity_in_stock: 7 },
      { size: 'Великий', quantity_in_stock: 8 },
    ],
    rug_type: 'Синтетичний',
    rug_material: 'Синтетика',
    rug_color: 'Зелений',
    rug_shape: 'Овальний',
    rug_country_of_origin: 'Китай',
    rug_pile_height: 9,
    rug_backing_material: 'Тканина',
    rug_height: 170,
    rug_sku: 'SKU101',
    rug_discounted_price: 75,
  },
  {
    category: 'Килими',
    manufacturer: 'Виробник 3',
    unit_price: 80,
    description: 'Опис четвертого килима',
    availability_status: 'В наявності',
    quantity_in_stock: 15,
    popularity_rating: 4.4,
    features: ['Функція 7', 'Функція 8'],
    product_image_url: 'url_to_image4.jpg',
    sizes: [
      { size: 'Маленький', quantity_in_stock: 7 },
      { size: 'Великий', quantity_in_stock: 8 },
    ],
    rug_type: 'Синтетичний',
    rug_material: 'Синтетика',
    rug_color: 'Зелений',
    rug_shape: 'Овальний',
    rug_country_of_origin: 'Китай',
    rug_pile_height: 9,
    rug_backing_material: 'Тканина',
    rug_height: 170,
    rug_sku: 'SKU101',
    rug_discounted_price: 75,
  },
  {
    category: 'Килими',
    manufacturer: 'Виробник 3',
    unit_price: 80,
    description: 'Опис четвертого килима',
    availability_status: 'В наявності',
    quantity_in_stock: 15,
    popularity_rating: 4.4,
    features: ['Функція 7', 'Функція 8'],
    product_image_url: 'url_to_image4.jpg',
    sizes: [
      { size: 'Маленький', quantity_in_stock: 7 },
      { size: 'Великий', quantity_in_stock: 8 },
    ],
    rug_type: 'Синтетичний',
    rug_material: 'Синтетика',
    rug_color: 'Зелений',
    rug_shape: 'Овальний',
    rug_country_of_origin: 'Китай',
    rug_pile_height: 9,
    rug_backing_material: 'Тканина',
    rug_height: 170,
    rug_sku: 'SKU101',
    rug_discounted_price: 75,
  },
  {
    category: 'Килими',
    manufacturer: 'Виробник 3',
    unit_price: 80,
    description: 'Опис четвертого килима',
    availability_status: 'В наявності',
    quantity_in_stock: 15,
    popularity_rating: 4.4,
    features: ['Функція 7', 'Функція 8'],
    product_image_url: 'url_to_image4.jpg',
    sizes: [
      { size: 'Маленький', quantity_in_stock: 7 },
      { size: 'Великий', quantity_in_stock: 8 },
    ],
    rug_type: 'Синтетичний',
    rug_material: 'Синтетика',
    rug_color: 'Зелений',
    rug_shape: 'Овальний',
    rug_country_of_origin: 'Китай',
    rug_pile_height: 9,
    rug_backing_material: 'Тканина',
    rug_height: 170,
    rug_sku: 'SKU101',
    rug_discounted_price: 75,
  },
  {
    category: 'Килими',
    manufacturer: 'Виробник 3',
    unit_price: 80,
    description: 'Опис четвертого килима',
    availability_status: 'В наявності',
    quantity_in_stock: 15,
    popularity_rating: 4.4,
    features: ['Функція 7', 'Функція 8'],
    product_image_url: 'url_to_image4.jpg',
    sizes: [
      { size: 'Маленький', quantity_in_stock: 7 },
      { size: 'Великий', quantity_in_stock: 8 },
    ],
    rug_type: 'Синтетичний',
    rug_material: 'Синтетика',
    rug_color: 'Зелений',
    rug_shape: 'Овальний',
    rug_country_of_origin: 'Китай',
    rug_pile_height: 9,
    rug_backing_material: 'Тканина',
    rug_height: 170,
    rug_sku: 'SKU101',
    rug_discounted_price: 75,
  },
];
